### ISSUE TITLE
[Feature]: Shortcut to move between word 

### ISSUE THREAD

**Issue by Fis-Ura** [lifebottle/TranslationApp#27]
### Contact Details

Pegi

### What is your request?

As a user, I want to be able to move between word faster.

using shift+arrow I want to be able to move between word instead of spaces

**Comment by Mc-muffin** [comment]
This is actually a bug, caused by swallowing every event under <kbd>ctrl</kbd>, so the regular <kbd>ctrl</kbd>+<kbd>key</kbd> shortcuts of the textbox never fire.
