### ISSUE TITLE
Bug : The listbox is not displaying properly the entries

### ISSUE THREAD

**Issue by fortiersteven** [lifebottle/TranslationApp#4]
### What Tales of Game are you working on?

Tales of Rebirth (PS2)

### Contact Details

Pegi

### What happened?

When I go inside file 10467.xml for the Story, the text on the listbox is not showing properly
![image](https://user-images.githubusercontent.com/74146408/179406871-08572911-b658-46fc-ae79-941981f7dcbb.png)

**Comment by Mc-muffin** [comment]
This is a problem with new line replacement leaving dangling `\r`

**Comment by fortiersteven** [comment]
Closing this one as @Fis-Ura said the issue is solved
