### ISSUE TITLE
[Feature]: Display listbox display by status instead of if empty

### ISSUE THREAD

**Issue by Fis-Ura** [lifebottle/TranslationApp#44]
In some cases we might need to remove the japanese and leave an empty string to be inserted, atm the list box doesn't display thoses strings, they display the japanese by default. 

![Image](https://user-images.githubusercontent.com/77898683/184731927-44895c5b-43fb-4685-b2e5-1fd1fbccde93.png)

**Comment by Fis-Ura** [comment]
@Mc-muffin  is this possible to have them be empty in the listbox ?

**Comment by Mc-muffin** [comment]
This was fixed by 772c086a455ea816a8ee05b64f2a563044252ad1
