### ISSUE TITLE
[Bug]: Display of To Do strings disseapears when Done status is ticked

### ISSUE THREAD

**Issue by Fis-Ura** [lifebottle/TranslationApp#58]
### What Tales of Game are you working on?

Tales of Rebirth (PS2)

### Contact Details

Pegi

### What happened?

For exemple in the story file 10197.xml when you tick all the status box except done you should have 5 strings, ticking the Done box will make the strings dissapears. Also the Done string do not show in the app.

**Comment by Mc-muffin** [comment]
Is this still a thing? This was before the UI change so it might no longer be valid

**Comment by Fis-Ura** [comment]
I think this issue has been solved
