### ISSUE TITLE
[Bug]: Display of & character in the Speaker list box not showing

### ISSUE THREAD

**Issue by Fis-Ura** [lifebottle/TranslationApp#59]
### What Tales of Game are you working on?

Tales of Rebirth (PS2)

### Contact Details

Pegi

### What happened?

Thw ascii version of the & character becomes a _ in the list box with all the strings, this was tested on the speaker-translate branch

![image](https://user-images.githubusercontent.com/77898683/195168421-6102a690-95c3-4913-b2c7-3a16fa242909.png)

**Comment by Fis-Ura** [comment]
![image](https://user-images.githubusercontent.com/77898683/195223922-b008faa0-a56e-49a3-8ad1-e1fad464d1d0.png)
this might be the reason it'S not showing

**Comment by Fis-Ura** [comment]
No change on this on 1.0.3

**Comment by Mc-muffin** [comment]
~This seems to be fixed~
Now it's fixed, closed it prematurely due to an error
