### ISSUE TITLE
[Bug]: Refresh Button revert the status of the first string to To Do when it was at Done

### ISSUE THREAD

**Issue by Fis-Ura** [lifebottle/TranslationApp#60]
### What Tales of Game are you working on?

Tales of Rebirth (PS2)

### Contact Details

Pegi

### What happened?

When hitting the refresh button on the speaker-translate branch. The first string in the listbox revert to the To Do status
![image](https://user-images.githubusercontent.com/77898683/195168964-855730dc-e703-464b-b057-420e4f8fa47d.png)

**Comment by Mc-muffin** [comment]
This one seems solved, feel free to reopen if not
