### ISSUE TITLE
[Bug]: Speaker listbox Height

### ISSUE THREAD

**Issue by Fis-Ura** [lifebottle/TranslationApp#67]
### What Tales of Game are you working on?

Tales of Rebirth (PS2)

### Contact Details

Pegi

### What happened?

The speaker text box height only adjust if you have strings in the Text section.
steps to reproduce. 
go to 10216
select speaker tab
click to show the "Done" string
still problematic
click on the text tab and then click on speaker tab
height was ajusted
![image](https://user-images.githubusercontent.com/77898683/211209281-6d11a002-09bd-4694-a192-6c1419e70aae.png)
![image](https://user-images.githubusercontent.com/77898683/211209290-dd1229f7-8a12-4a9a-b07d-c9f990f85af5.png)

**Comment by Fis-Ura** [comment]
this is still an issue on 2023-04-11 
![image](https://user-images.githubusercontent.com/77898683/231266707-2f9a544f-bebb-4bff-8b1a-fc78c2980844.png)

**Comment by Mc-muffin** [comment]
Fixed by ad89491
