### ISSUE TITLE
Save to XML issue with newline

### ISSUE THREAD

**Issue by Fis-Ura** [lifebottle/TranslationApp#8]
### What Tales of Game are you working on?

Tales of Rebirth (PS2)

### Contact Details

Pegi

### What happened?

using the Function Save to XML creates new line with the "book string"

![image](https://user-images.githubusercontent.com/77898683/179414110-89d34040-84fe-4911-925a-3cb5ad28306e.png)

![image](https://user-images.githubusercontent.com/77898683/179414174-46ff7b7e-c5d3-4f31-aab2-219c5704c136.png)

**Comment by Fis-Ura** [comment]
Seems to be related to the Speed:00 Tag

**Comment by Fis-Ura** [comment]
![image](https://user-images.githubusercontent.com/77898683/179415160-f597c25c-8f3f-499a-9306-d0e6f3fc5160.png)

**Comment by Mc-muffin** [comment]
This is actually related to #4

**Comment by fortiersteven** [comment]
Solved based on @Fis-Ura validations
