### ISSUE TITLE
[Bug]: Translation App

### ISSUE THREAD

**Issue by Kevan33** [lifebottle/TranslationApp#80]
### What Tales of Game are you working on?

NDX
### Contact Details

509445218488287243

### What happened?

This version of the app lets me search for English text under “All” but not via each individual section, like Menu, Skits, Story. Japanese search doesn't seem to work at all. Build v1.0.8, pull request 0078.16, commiy d943cd0

**Comment by Mc-muffin** [comment]
Fixed via 6484dc757963652be1510dc3e70daf40b3e954a3
